spring.application.name=order-service
server.port=8081

#Config server url
spring.cloud.config.uri=http://localhost:8888


# Enable expose refresh endpoint
management.endpoints.web.exposure.include=refresh,health,info
