spring.application.name=config-server
server.port=8888

# Config server even faster we can also enable clone-on-start
# Config server will download git repo once when starting, faster for large config
spring.cloud.config.server.git.clone-on-start=true

# Many apps at root level (config files stored in folder structure)
spring.cloud.config.server.git.search-paths=*

# Where to find config files (Git repo link or local folder)
spring.cloud.config.server.git.uri=https://github.com/sarmanic90/SpringBootMicroservice/tree/main/config-files-repo

# ************************** Local folder for config files **************************
#spring.profiles.active=native
#spring.cloud.config.server.native.search-locations=file:///path/to/local/config-folder
# ************************** Local folder for config files **************************
